---
name: Build and Deploy React App to GitHub Pages
on:
  push:
    branches: [ master ]
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Deploy
      run: |
        git config --global user.name 'juancr5'
        git config --global user.email 'juancr5@hotmail.com'
        git remote set-url origin https://x-access-token:${{ secrets.TOKEN_GIT }}@github.com/${{ github.repository }}    
        npm run deploy