---
name: Build and Deploy React App to GitHub Pages
on:
  push:
    branches: [ master ]
# jobs:
#   build-and-deploy:
#     name: Build and Deploy
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout
#       uses: actions/checkout@v2

#     - name: Build
#       run: npm install
    
#     - name: Test
#       run: npm run cypress:run

#     - name: Deploy
#       uses: crazy-max/ghaction-github-pages@v1
#       with:
#         target_branch: gh-pages
#         build_dir: build
#       env:
          # GITHUB_TOKEN: ${{ secrets.TOKEN_GIT }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set Node.js 12
      uses: actions/setup-node@v1
      with:
        version: 12.x
    - name: Install    
      run: npm install
    - name: Build
      run: CI=false npm run build
    - name: Deploy
      uses: crazy-max/ghaction-github-pages@v1
      with:
        target_branch: gh-pages
        build_dir: build
      env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GIT }}

    # - name: Deploy
    #   uses: /juancr5/Old_Wave-React-Front
    #   with:
    #     branch: gh-pages
    #     folder: site
    #     ssh-key: ${{ secrets.TOKEN_GIT }}
    #   run: npm run deploy

    # - name: Deploy
    #   run: |
    #     git config --global user.name 'juancr5'
    #     git config --global user.email 'juancr5@hotmail.com'
    #     git remote set-url origin https://$github@github.com/juancr5/Old_Wave-React-Front
    #     npm run deploy

    # - name: Deploy
    #     github_token: ${{ secrets.TOKEN_GIT }}
    #     publish_dir: build